name: Build & Test

on: push

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update 1> /dev/null
        sudo apt upgrade 1> /dev/null
        sudo apt-get install libgtkmm-3.0-dev libjsoncpp-dev libgtest-dev libgmock-dev clang-tidy cppcheck clang-format 1> /dev/null
    
    - name: Configure CMake
      run: cmake .

    - name: Format Code
      # Formats code using clang-format (version 14 or higher required)
      run: make FORMAT

    - name: Build AppAnvil
      # Builds the 'appanvil' binary into the ./dist folder
      run: make

    - name: Build Tests
      # Builds the unit tests into the ./dist folder
      run: make test

    - name: Upload Binaries as Artifacts
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
        if-no-files-found: error

  test:
    runs-on: ubuntu-22.04
    needs: [build]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update 1> /dev/null
        sudo apt upgrade 1> /dev/null
        sudo apt-get install xvfb libgtkmm-3.0-dev libjsoncpp-dev 1> /dev/null

    - name: Download Binary Artifacts
      uses: actions/download-artifact@master
      with:
        name: dist
        path: dist

    - name: Make Tests Executable
      run: chmod +x ./dist/test

    - name: Test
      # Run the unit tests
      run: xvfb-run --auto-servernum ./dist/test